---
title: "Membrane permeabilization: Tidy data"
author: "Stelios Serghiou"
date: "`r format(Sys.time(), '%a, %b %d, %Y')`"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

# Setup

## Imports

```{r}
library(dplyr)
library(magrittr)
library(readr)
```

## Parameters

```{r}
# Source locations
src_dirname <- "../../../data/extracted/exp=membrane-permeabilization/"

# Destination locations
dst_dirname <- "../../../data/tidy/exp=membrane-permeabilization/"
```

------------------------------------------------------------------------

# Read

```{r}
# Get all CSV files
csv_files <- list.files(
  path = src_dirname,
  pattern = "*.csv",
  full.names = T,
  recursive = T
)

# Read all csv files
study_ <- read_csv(csv_files)
```

------------------------------------------------------------------------

# Conform

Create file.

```{r}
study <- study_
```

Inspect file.

```{r}
glimpse(study)
```

Remove unwanted columns.

```{r}
# Unwanted columns
unwanted_cols <- c("...1")

# Remove
study %<>% select(-all_of(unwanted_cols))
```

Rename columns.

```{r}
# Column names
new_old <- c(
  file_name = "Label",
  "area_px2" = "Area",
  mean_intensity = "Mean",
  min_intensity = "Min",
  max_intensity = "Max",
  integrated_density = "IntDen",
  raw_integrated_density = "RawIntDen"
)

study %<>% 
  rename(any_of(new_old))
```

Create columns.

```{r}
# Create columns
study %<>% 
  mutate(
    condition = stringr::str_replace(file_name, "^(.*)\\.tif:([0-9]+)$", "\\1"),
    channel = stringr::str_replace(file_name, "^(.*)\\.tif:([0-9]+)$", "\\2")
  ) %>%
  relocate(condition:channel, .after = file_name)
```

Glimpse.

```{r}
glimpse(study)
```

------------------------------------------------------------------------

# Write

```{r}
# Create file path
today <- format(Sys.time(), "%Y-%m-%d")
filepath <- file.path(dst_dirname, paste0(today, ".csv"))

# Write
write_csv(study, filepath)
```

------------------------------------------------------------------------

# Documentation

## Session info

```{r}
print(sessionInfo(), locale = F)
```

## References

```{r}
(.packages()) %>% sort %>% lapply(citation) %>% lapply(c) %>% unique
```
